name: aimat
channels:
  - defaults
  - conda-forge
dependencies:
  - pip=21.0.1
  - python=3.8
  - rdkit=2021.03.2
  - pip:
      - bokeh==2.3.2
      - jupyter==1.0.0
      - matplotlib==3.4.2
      - nbgrader==0.6.2
      - networkx==2.5.1
      - numpy==1.19.5
      - pandas==1.2.4
      - pygame==2.0.1
      - pymysql==1.0.2
      - pyvis==0.1.9
      - pyyaml==5.4.1
      - seaborn==0.11.1
      - scikit-learn==0.24.2
      - tensorflow==2.5.0
      - tables==3.6.1
      - xlrd==2.0.1
